### ISSUE TITLE
[win32] tor.exe doesn't stop after close

### ISSUE THREAD

**Issue by internetguy487** [GitSquared/ORNE-client#1]
hi,

i heard about your project and i wanted to test it, i explored a bit the ny's sneak peek, a pretty good start =)
i tested the latest version, there's a problem when you exit the app, the background tor.exe doesn't stop (windows only)
pls fix it, and good luck for the future :)

-random internet guy

**Comment by internetguy487** [comment]
@GitSquared

**Comment by GitSquared** [comment]
@internetguy487 Hey,
Thanks for the info. I'll be on it. Fix expected within ~12 hours.

Remember to subscribe to the newsletter on the project's website if you want to receive updates on the releases. We're expecting a core 1.0 around July, and then we'll start building "modules" (Social network, email, password manager, etc) on top of it. #hypetrain

Again, thanks for the info.

**Comment by internetguy487** [comment]
@GitSquared haha, #hypetrain x) waiting for the fix o/

**Comment by GitSquared** [comment]
Tested under win32:
tor.exe is launched when running installer, and never closed.
Need testing.

**Comment by GitSquared** [comment]
New info:

tor.exe isn't stopped properly after running ORNE for the first time (with installer) and closing it with alt+f4. (unconfirmed)
Reports of random unclosed tor process.

UPDATE: After digging a bit, it seems like **Tor refuse to close itself if it's still trying to connect.**
This means that if the ORNE window is closed too early, tor keeps running it the background.
**This issue may be extended to *nix platforms. Testing ahead.**
